// components/endorsements/EndorsementDetailModal.jsx - WhatsApp-style Story View (Green Theme)

import React, { useState, useEffect, useRef, useCallback } from "react";
import styled, { keyframes } from "styled-components";
import {
  X,
  Heart,
  MessageCircle,
  TrendingUp,
  Clock,
  Play,
  Send,
  Volume2,
  VolumeX,
} from "lucide-react";
import api from "../../api/api";
import API from "../../api/config";

const slideUp = keyframes`
  from { transform: translateY(100%); opacity: 0; }
  to { transform: translateY(0); opacity: 1; }
`;

const fadeIn = keyframes`
  from { opacity: 0; transform: scale(0.98); }
  to { opacity: 1; transform: scale(1); }
`;

const glowPulse = keyframes`
  0% { box-shadow: 0 0 0 0 rgba(34, 197, 94, 0.4); }
  70% { box-shadow: 0 0 0 8px rgba(34, 197, 94, 0); }
  100% { box-shadow: 0 0 0 0 rgba(34, 197, 94, 0); }
`;

import { buildImageUrl } from "../../utils/imageUtils";

// Check if message is auto-generated
const isAutoGeneratedMessage = (message, mediaType) => {
  if (!message) return true;
  const autoMessages = [
    "📷 Photo", "📹 Video", "💬 Support message", "Support message",
    "Photo", "Video", "📸 Photo", "🎥 Video"
  ];
  if ((mediaType === "image" || mediaType === "video") && autoMessages.includes(message.trim())) {
    return true;
  }
  return false;
};

// Get display message (only real user messages)
const getDisplayMessage = (story) => {
  const { message, media_type } = story;
  if (message && !isAutoGeneratedMessage(message, media_type)) {
    return message;
  }
  return null;
};

// Styled Components - Green Theme
const FullScreenOverlay = styled.div`
  position: fixed;
  inset: 0;
  background: #000;
  z-index: 100000;
  display: flex;
  flex-direction: column;
  overflow: hidden;
`;

const ProgressContainer = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  display: flex;
  gap: 3px;
  z-index: 100;
  padding: 6px 10px;
  background: rgba(0, 0, 0, 0.4);
`;

const ProgressTrack = styled.div`
  flex: 1;
  height: 3px;
  background: rgba(255, 255, 255, 0.3);
  border-radius: 3px;
  overflow: hidden;
`;

const ProgressFill = styled.div`
  height: 100%;
  background: ${(props) => (props.$active ? "#22c55e" : "rgba(255,255,255,0.6)")};
  width: ${(props) => props.$width}%;
  transition: width 0.05s linear;
  border-radius: 3px;
`;

const StoryHeader = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  padding: 50px 16px 20px;
  z-index: 50;
  background: linear-gradient(to bottom, rgba(0, 0, 0, 0.7), transparent);
  display: flex;
  align-items: center;
  justify-content: space-between;
`;

const UserInfo = styled.div`
  display: flex;
  align-items: center;
  gap: 12px;
`;

const UserAvatar = styled.img`
  width: 44px;
  height: 44px;
  border-radius: 50%;
  object-fit: cover;
  background: #1a1a1a;
  border: 2px solid #22c55e;
  animation: ${glowPulse} 2s infinite;
`;

const UserTextInfo = styled.div`
  display: flex;
  flex-direction: column;
`;

const UserName = styled.div`
  font-weight: 700;
  font-size: 0.9rem;
  color: white;
`;

const UserDetail = styled.div`
  font-size: 0.65rem;
  color: rgba(255, 255, 255, 0.6);
  display: flex;
  align-items: center;
  gap: 4px;
  margin-top: 2px;
`;

const CloseBtn = styled.button`
  background: transparent;
  border: none;
  color: white;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: none;
`;

const FullScreenMedia = styled.div`
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #000;

  img {
    width: 100%;
    height: 100%;
    object-fit: contain;
  }

  video {
    width: 100%;
    height: 100%;
    object-fit: contain;
  }
`;

const GradientOverlay = styled.div`
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: linear-gradient(
    to top,
    rgba(0, 0, 0, 0.9) 0%,
    rgba(0, 0, 0, 0.5) 40%,
    transparent 100%
  );
  height: 40%;
  z-index: 30;
  pointer-events: none;
`;

const BottomMessage = styled.div`
  position: absolute;
  bottom: 100px;
  left: 0;
  right: 0;
  text-align: center;
  z-index: 40;
  padding: 0 20px;
`;

const MessageText = styled.div`
  font-size: 1.2rem;
  line-height: 1.4;
  font-weight: 500;
  color: white;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.8);
  max-width: 85%;
  margin: 0 auto;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(8px);
  padding: 12px 20px;
  border-radius: 30px;
  animation: ${fadeIn} 0.3s ease;
`;

const CenteredMessageContainer = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  z-index: 35;
  background: linear-gradient(135deg, #0a2e1a, #0a2e1a);
`;

const CenteredText = styled.div`
  font-size: 1.8rem;
  line-height: 1.4;
  font-weight: 500;
  color: white;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
  max-width: 85%;
  margin: 0 auto;
  padding: 20px;
  animation: ${fadeIn} 0.3s ease;
  word-wrap: break-word;
`;

const EndorsementMeta = styled.div`
  position: absolute;
  bottom: 30px;
  left: 0;
  right: 0;
  display: flex;
  justify-content: center;
  gap: 32px;
  z-index: 40;
`;

const MetaItem = styled.div`
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.75rem;
  color: white;
  text-shadow: 0 1px 4px rgba(0, 0, 0, 0.5);
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(8px);
  padding: 6px 14px;
  border-radius: 30px;

  svg {
    width: 14px;
    height: 14px;
    color: #22c55e;
  }
`;

const RightActions = styled.div`
  position: absolute;
  right: 12px;
  bottom: 30%;
  display: flex;
  flex-direction: column;
  gap: 16px;
  z-index: 50;
`;

const ActionButton = styled.button`
  display: flex;
  flex-direction: column;
  align-items: center;
  background: transparent;
  backdrop-filter: none;
  border: none;
  padding: 8px;
  color: white;
  gap: 4px;
  cursor: pointer;
  min-width: 52px;
  border-radius: 30px;
  transition: none;

  span {
    font-size: 0.6rem;
    font-weight: 600;
    text-shadow: 0 1px 2px rgba(0,0,0,0.5);
  }

  &:active {
    transform: scale(0.95);
  }
`;

const CountSpan = styled.span`
  font-size: 0.6rem;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.9);
`;

const NavigationZone = styled.div`
  position: absolute;
  top: 0;
  bottom: 0;
  width: 25%;
  z-index: 45;
  cursor: pointer;
`;

const LeftZone = styled(NavigationZone)`
  left: 0;
`;
const RightZone = styled(NavigationZone)`
  right: 0;
`;

const VolumeButton = styled.button`
  position: absolute;
  bottom: 100px;
  right: 16px;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(8px);
  border: none;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  z-index: 50;
  color: white;

  &:hover {
    background: rgba(0, 0, 0, 0.7);
  }
`;

const CommentsModalOverlay = styled.div`
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #0a0a0a;
  height: 70vh;
  z-index: 100001;
  display: flex;
  flex-direction: column;
  animation: ${slideUp} 0.3s ease-out;
  border-radius: 20px 20px 0 0;
`;

const CommentsModalHeader = styled.div`
  padding: 16px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
`;

const CommentsList = styled.div`
  flex: 1;
  overflow-y: auto;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;

  &::-webkit-scrollbar {
    width: 4px;
  }

  &::-webkit-scrollbar-track {
    background: #1a1a1a;
  }

  &::-webkit-scrollbar-thumb {
    background: #22c55e;
    border-radius: 4px;
  }
`;

const CommentItem = styled.div`
  display: flex;
  gap: 12px;
  animation: fadeIn 0.2s ease;
`;

const CommentAvatar = styled.div`
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: linear-gradient(135deg, #22c55e, #15803d);
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-weight: bold;
  flex-shrink: 0;
`;

const CommentContent = styled.div`
  flex: 1;
`;

const CommentHeader = styled.div`
  display: flex;
  align-items: baseline;
  gap: 8px;
  margin-bottom: 6px;
  flex-wrap: wrap;
`;

const CommentUserName = styled.span`
  font-weight: 800;
  font-size: 1rem;
  color: #22c55e;
`;

const CommentTime = styled.span`
  font-size: 0.65rem;
  color: rgba(255, 255, 255, 0.5);
`;

const CommentText = styled.div`
  font-size: 1.15rem;
  color: white;
  line-height: 1.5;
  font-weight: 500;
  word-break: break-word;
`;

const CommentActions = styled.div`
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 6px;
`;

const LikeButton = styled.button`
  background: none;
  border: none;
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.7rem;
  color: ${(props) => (props.$liked ? "#ef4444" : "rgba(255, 255, 255, 0.5)")};
  cursor: pointer;
  padding: 4px 8px;
  border-radius: 20px;
  transition: all 0.2s;

  &:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  svg {
    width: 14px;
    height: 14px;
  }
`;

const CommentInputWrapper = styled.div`
  padding: 16px;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  background: #0a0a0a;
`;

const InputForm = styled.form`
  display: flex;
  gap: 12px;
  align-items: flex-end;
`;

const CommentInput = styled.textarea`
  flex: 1;
  background: #1a1a1a;
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 20px;
  padding: 12px 16px;
  color: white;
  font-size: 0.85rem;
  resize: none;
  min-height: 44px;
  max-height: 100px;
  font-family: inherit;

  &:focus {
    outline: none;
    border-color: #22c55e;
  }

  &::placeholder {
    color: rgba(255, 255, 255, 0.4);
    font-size: 0.85rem;
  }
`;

const SendButton = styled.button`
  background: #22c55e;
  border: none;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    background: #16a34a;
    transform: scale(1.05);
  }

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
  }
`;

const EmptyComments = styled.div`
  text-align: center;
  color: rgba(255, 255, 255, 0.5);
  padding: 40px 20px;
  font-size: 0.85rem;
`;

const EndorsementDetailModal = ({
  isOpen,
  onClose,
  endorsements = [],
  initialIndex = 0,
  currentUser,
  onCommentsUpdate,
}) => {
  const [currentIndex, setCurrentIndex] = useState(initialIndex);
  const [progress, setProgress] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  const [showComments, setShowComments] = useState(false);
  const [likesState, setLikesState] = useState({});
  const [likesCountState, setLikesCountState] = useState({});
  const [commentsState, setCommentsState] = useState({});
  const [commentsLoading, setCommentsLoading] = useState({});
  const [newComment, setNewComment] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isMuted, setIsMuted] = useState(true);
  const [touchStart, setTouchStart] = useState(null);

  const timerRef = useRef(null);
  const videoRef = useRef(null);
  const STORY_DURATION = 5000;

  const current = endorsements[currentIndex];

  const loadComments = useCallback(async (storyId) => {
    if (!storyId) return;
    setCommentsLoading((prev) => ({ ...prev, [storyId]: true }));
    try {
      const response = await api.get(`/endorsements/${storyId}/comments?t=${Date.now()}`);
      let comments = [];
      if (response.data?.data?.comments) {
        comments = response.data.data.comments;
      } else if (response.data?.comments) {
        comments = response.data.comments;
      } else if (Array.isArray(response.data?.data)) {
        comments = response.data.data;
      } else if (Array.isArray(response.data)) {
        comments = response.data;
      }
      setCommentsState((prev) => ({ ...prev, [storyId]: comments }));
    } catch (error) {
      setCommentsState((prev) => ({ ...prev, [storyId]: [] }));
    } finally {
      setCommentsLoading((prev) => ({ ...prev, [storyId]: false }));
    }
  }, []);

  useEffect(() => {
    if (isOpen && current?.id) {
      loadComments(current.id);
      if (current.likes !== undefined && likesCountState[current.id] === undefined) {
        setLikesCountState((prev) => ({
          ...prev,
          [current.id]: current.likes || 0,
        }));
      }
    }
  }, [isOpen, current?.id, loadComments, current?.likes]);

  const getAvatarUrl = (item) => {
    // image_url is the story MEDIA, not the user's profile picture
    // Always use a generated avatar based on the user's name
    return `https://ui-avatars.com/api/?name=${encodeURIComponent(item?.user_name || "User")}&background=22c55e&color=fff&size=100`;
  };

  const getMediaUrl = (item) => {
    if (item?.image_url) {
      return buildImageUrl(item.image_url);
    }
    return null;
  };

  const formatDate = (dateString) => {
    if (!dateString) return "Recently";
    const date = new Date(dateString);
    const now = new Date();
    const diffMins = Math.floor((now - date) / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);

    if (diffMins < 1) return "Just now";
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  const capitalizeFirst = (str) => {
    if (!str) return "";
    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
  };

  useEffect(() => {
    if (isOpen) {
      setCurrentIndex(initialIndex);
      setProgress(0);
      setIsPaused(false);
    }
  }, [isOpen, initialIndex]);

  const handleNext = useCallback(() => {
    if (currentIndex < endorsements.length - 1) {
      setCurrentIndex((prev) => prev + 1);
      setProgress(0);
    } else {
      onClose();
    }
  }, [currentIndex, endorsements.length, onClose]);

  const handlePrev = useCallback(() => {
    if (currentIndex > 0) {
      setCurrentIndex((prev) => prev - 1);
      setProgress(0);
    }
  }, [currentIndex]);

  const handleTouchStart = (e) => {
    setTouchStart(e.touches[0].clientX);
  };

  const handleTouchEnd = (e) => {
    if (!touchStart) return;
    const touchEnd = e.changedTouches[0].clientX;
    const diff = touchStart - touchEnd;

    if (Math.abs(diff) > 50) {
      if (diff > 0) {
        handleNext();
      } else {
        handlePrev();
      }
    }
    setTouchStart(null);
  };

  useEffect(() => {
    if (!isOpen || isPaused || showComments) return;

    const interval = 100;
    const step = 100 / (STORY_DURATION / interval);

    timerRef.current = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          handleNext();
          return 0;
        }
        return prev + step;
      });
    }, interval);

    return () => clearInterval(timerRef.current);
  }, [isOpen, isPaused, showComments, handleNext]);

  const handleLike = async () => {
    if (!current) return;
    const storyId = current.id;
    const isLiked = likesState[storyId];
    const currentLikes = likesCountState[storyId] || current.likes || 0;

    setLikesState((prev) => ({ ...prev, [storyId]: !isLiked }));
    setLikesCountState((prev) => ({
      ...prev,
      [storyId]: isLiked ? currentLikes - 1 : currentLikes + 1,
    }));

    try {
      const response = await api.post(`/endorsements/${storyId}/like`, {
        user_id: currentUser?.id || "anonymous"
      });
      if (response.success) {
        setLikesState((prev) => ({ ...prev, [storyId]: response.liked }));
        setLikesCountState((prev) => ({
          ...prev,
          [storyId]: response.likes,
        }));
      }
    } catch (e) {
      setLikesState((prev) => ({ ...prev, [storyId]: isLiked }));
      setLikesCountState((prev) => ({ ...prev, [storyId]: currentLikes }));
    }
  };

  const handleSendComment = async () => {
    if (!current || !newComment.trim() || isSubmitting) return;

    const storyId = current.id;
    const tempId = `temp_${Date.now()}`;

    setIsSubmitting(true);

    const newCommentObj = {
      id: tempId,
      user_id: currentUser?.id || "anonymous",
      user_name: currentUser?.name || "Anonymous",
      comment: newComment.trim(),
      created_at: new Date().toISOString(),
      likes: 0,
      liked: false,
    };

    setCommentsState((prev) => ({
      ...prev,
      [storyId]: [...(prev[storyId] || []), newCommentObj],
    }));

    setNewComment("");

    try {
      const response = await api.post(`/endorsements/${storyId}/comments`, {
        user_id: currentUser?.id || "anonymous",
        user_name: currentUser?.name || "Anonymous",
        comment: newComment.trim(),
      });

      if (response.success && response.data) {
        setCommentsState((prev) => ({
          ...prev,
          [storyId]: prev[storyId].map((c) =>
            c.id === tempId ? response.data : c
          ),
        }));
      } else {
        setCommentsState((prev) => ({
          ...prev,
          [storyId]: prev[storyId].filter((c) => c.id !== tempId),
        }));
      }
    } catch (error) {
      setCommentsState((prev) => ({
        ...prev,
        [storyId]: prev[storyId].filter((c) => c.id !== tempId),
      }));
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleLikeComment = async (commentId) => {
    if (!current) return;

    try {
      const response = await api.post(`/endorsements/${current.id}/comments/${commentId}/like`, {
        user_id: currentUser?.id || "anonymous"
      });

      if (response.success) {
        setCommentsState((prev) => ({
          ...prev,
          [current.id]: prev[current.id].map((c) =>
            c.id === commentId
              ? { ...c, liked: response.liked, likes: response.likes }
              : c
          ),
        }));
      }
    } catch (error) {
      // Silent fail
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendComment();
    }
  };

  const handlePause = () => setIsPaused(true);
  const handleResume = () => setIsPaused(false);

  if (!isOpen || !current) return null;

  const currentLikesCount = likesCountState[current.id] !== undefined
    ? likesCountState[current.id]
    : current.likes || 0;

  const currentCommentsCount = commentsState[current.id]?.length || 0;
  const mediaUrl = getMediaUrl(current);
  const hasMedia = mediaUrl && (current.media_type === "image" || current.media_type === "video");
  const isVideo = hasMedia && current.media_type === "video";
  const displayMessage = getDisplayMessage(current);

  return (
    <>
      <FullScreenOverlay
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
      >
        <ProgressContainer>
          {endorsements.map((_, idx) => (
            <ProgressTrack key={idx}>
              <ProgressFill
                $active={idx === currentIndex}
                $width={idx < currentIndex ? 100 : idx === currentIndex ? progress : 0}
              />
            </ProgressTrack>
          ))}
        </ProgressContainer>

        <StoryHeader>
          <UserInfo>
            <UserAvatar src={getAvatarUrl(current)} alt={current.user_name} />
            <UserTextInfo>
              <UserName>{capitalizeFirst(current.user_name || "Anonymous")}</UserName>
              <UserDetail>
                <Clock size={10} />
                <span>{formatDate(current.created_at)}</span>
              </UserDetail>
            </UserTextInfo>
          </UserInfo>
          <CloseBtn onClick={onClose}>
            <X size={24} />
          </CloseBtn>
        </StoryHeader>

        <LeftZone onClick={handlePrev} onMouseEnter={handlePause} onMouseLeave={handleResume} />
        <RightZone onClick={handleNext} onMouseEnter={handlePause} onMouseLeave={handleResume} />

        {hasMedia ? (
          <>
            <FullScreenMedia onClick={handlePause}>
              {isVideo ? (
                <video
                  ref={videoRef}
                  src={mediaUrl}
                  autoPlay
                  loop
                  playsInline
                  muted={isMuted}
                />
              ) : (
                <img src={mediaUrl} alt="Story" />
              )}
            </FullScreenMedia>
            <GradientOverlay />

            {isVideo && (
              <VolumeButton onClick={() => setIsMuted(!isMuted)}>
                {isMuted ? <VolumeX size={18} /> : <Volume2 size={18} />}
              </VolumeButton>
            )}
          </>
        ) : null}

        {displayMessage && hasMedia && (
          <BottomMessage>
            <MessageText>{displayMessage}</MessageText>
          </BottomMessage>
        )}

        {displayMessage && !hasMedia && (
          <CenteredMessageContainer>
            <CenteredText>{displayMessage}</CenteredText>
          </CenteredMessageContainer>
        )}

        <EndorsementMeta>
          <MetaItem>
            <Heart size={14} />
            <span>{currentLikesCount}</span>
          </MetaItem>
          <MetaItem>
            <MessageCircle size={14} />
            <span>{currentCommentsCount}</span>
          </MetaItem>
        </EndorsementMeta>

        <RightActions>
          <ActionButton onClick={handleLike} onMouseEnter={handlePause} onMouseLeave={handleResume}>
            <Heart
              size={22}
              fill={likesState[current.id] ? "#ef4444" : "none"}
              color={likesState[current.id] ? "#ef4444" : "white"}
            />
            <span>Like</span>
            <CountSpan>{currentLikesCount}</CountSpan>
          </ActionButton>

          <ActionButton onClick={() => setShowComments(true)} onMouseEnter={handlePause} onMouseLeave={handleResume}>
            <MessageCircle size={22} />
            <span>Chat</span>
            <CountSpan>{currentCommentsCount}</CountSpan>
          </ActionButton>

          <ActionButton onMouseEnter={handlePause} onMouseLeave={handleResume}>
            <TrendingUp size={22} color="#fbbf24" />
            <span>Boost</span>
            <CountSpan>{current.boost_count || 0}</CountSpan>
          </ActionButton>
        </RightActions>

        {showComments && (
          <CommentsModalOverlay>
            <CommentsModalHeader>
              <div style={{ color: "white", fontWeight: "bold", fontSize: "1rem" }}>
                Comments ({currentCommentsCount})
              </div>
              <CloseBtn onClick={() => setShowComments(false)}>
                <X size={20} />
              </CloseBtn>
            </CommentsModalHeader>

            <CommentsList>
              {commentsLoading[current.id] ? (
                <div style={{ padding: "40px", textAlign: "center", color: "white" }}>
                  Loading comments...
                </div>
              ) : commentsState[current.id]?.length === 0 ? (
                <EmptyComments>No comments yet. Be the first to comment!</EmptyComments>
              ) : (
                commentsState[current.id]?.map((comment) => (
                  <CommentItem key={comment.id}>
                    <CommentAvatar>
                      {comment.user_name?.charAt(0).toUpperCase() || "U"}
                    </CommentAvatar>
                    <CommentContent>
                      <CommentHeader>
                        <CommentUserName>{comment.user_name || "Anonymous"}</CommentUserName>
                        <CommentTime>{formatDate(comment.created_at)}</CommentTime>
                      </CommentHeader>
                      <CommentText>{comment.comment}</CommentText>
                      <CommentActions>
                        <LikeButton
                          $liked={comment.liked}
                          onClick={() => handleLikeComment(comment.id)}
                        >
                          <Heart size={14} fill={comment.liked ? "#ef4444" : "none"} />
                          <span>{comment.likes || 0}</span>
                        </LikeButton>
                      </CommentActions>
                    </CommentContent>
                  </CommentItem>
                ))
              )}
            </CommentsList>

            <CommentInputWrapper>
              <InputForm onSubmit={(e) => { e.preventDefault(); handleSendComment(); }}>
                <CommentInput
                  placeholder="Write a comment..."
                  value={newComment}
                  onChange={(e) => setNewComment(e.target.value)}
                  onKeyPress={handleKeyPress}
                  rows={1}
                />
                <SendButton type="submit" disabled={!newComment.trim() || isSubmitting}>
                  <Send size={18} color="white" />
                </SendButton>
              </InputForm>
            </CommentInputWrapper>
          </CommentsModalOverlay>
        )}
      </FullScreenOverlay>
    </>
  );
};

export default EndorsementDetailModal;