// components/endorsements/EndorsementDetailModal.jsx - Clean Professional Story View
import React, { useState, useEffect, useRef, useCallback } from "react";
import styled, { keyframes } from "styled-components";
import {
  X,
  Heart,
  MessageCircle,
  TrendingUp,
  Clock,
  Play,
  Send,
} from "lucide-react";
import api from "../../api/api";
import API from "../../api/config";

const slideUp = keyframes`
  from { transform: translateY(100%); opacity: 0; }
  to { transform: translateY(0); opacity: 1; }
`;

const fadeIn = keyframes`
  from { opacity: 0; transform: scale(0.98); }
  to { opacity: 1; transform: scale(1); }
`;

const glowPulse = keyframes`
  0% { box-shadow: 0 0 0 0 rgba(220, 38, 38, 0.4); }
  70% { box-shadow: 0 0 0 8px rgba(220, 38, 38, 0); }
  100% { box-shadow: 0 0 0 0 rgba(220, 38, 38, 0); }
`;

// Helper function to build image URL
const buildImageUrl = (imageUrl) => {
  if (!imageUrl) return null;
  if (imageUrl.startsWith("http://") || imageUrl.startsWith("https://")) {
    return imageUrl;
  }
  const cleanPath = imageUrl.startsWith("/") ? imageUrl : `/${imageUrl}`;
  return `${API.IMAGES}${cleanPath}`;
};

// Check if message is auto-generated
const isAutoGeneratedMessage = (message, mediaType) => {
  if (!message) return true;
  const autoMessages = [
    "📷 Photo",
    "📹 Video",
    "💬 Support message",
    "Support message",
    "Photo",
    "Video",
  ];
  if (
    (mediaType === "image" || mediaType === "video") &&
    autoMessages.includes(message.trim())
  ) {
    return true;
  }
  return false;
};

// Get display message (only real user messages)
const getDisplayMessage = (story) => {
  const { message, media_type, phrase } = story;
  if (message && !isAutoGeneratedMessage(message, media_type)) {
    return message;
  }
  if (phrase && !isAutoGeneratedMessage(phrase, media_type)) {
    return phrase;
  }
  return null;
};

// Styled Components
const FullScreenOverlay = styled.div`
  position: fixed;
  inset: 0;
  background: #000;
  z-index: 100000;
  display: flex;
  flex-direction: column;
  overflow: hidden;
`;

const ProgressContainer = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  display: flex;
  gap: 2px;
  z-index: 100;
  padding: 4px 8px;
  background: rgba(0, 0, 0, 0.3);
`;

const ProgressTrack = styled.div`
  flex: 1;
  height: 2px;
  background: rgba(255, 255, 255, 0.2);
  overflow: hidden;
`;

const ProgressFill = styled.div`
  height: 100%;
  background: ${(props) => (props.$active ? "#dc2626" : "white")};
  width: ${(props) => props.$width}%;
  transition: width 0.05s linear;
`;

const StoryHeader = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  padding: 48px 16px 20px;
  z-index: 50;
  background: linear-gradient(to bottom, rgba(0, 0, 0, 0.6), transparent);
  display: flex;
  align-items: center;
  justify-content: space-between;
`;

const UserInfo = styled.div`
  display: flex;
  align-items: center;
  gap: 12px;
`;

const UserAvatar = styled.img`
  width: 48px;
  height: 48px;
  border-radius: 50%;
  object-fit: cover;
  background: #1a1a1a;
  border: 2px solid #dc2626;
  animation: ${glowPulse} 2s infinite;
`;

const UserTextInfo = styled.div`
  display: flex;
  flex-direction: column;
`;

const UserName = styled.div`
  font-weight: 700;
  font-size: 0.9rem;
  color: white;
`;

const UserDetail = styled.div`
  font-size: 0.65rem;
  color: rgba(255, 255, 255, 0.5);
  display: flex;
  align-items: center;
  gap: 4px;
  margin-top: 2px;
`;

const CloseBtn = styled.button`
  background: rgba(0, 0, 0, 0.5);
  border: none;
  color: white;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    background: rgba(0, 0, 0, 0.8);
  }
`;

const FullScreenMedia = styled.div`
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #000;

  img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  video {
    width: 100%;
    height: 100%;
    object-fit: contain;
  }
`;

const GradientOverlay = styled.div`
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: linear-gradient(
    to top,
    rgba(0, 0, 0, 0.95) 0%,
    rgba(0, 0, 0, 0.7) 30%,
    rgba(0, 0, 0, 0.2) 60%,
    transparent 100%
  );
  height: 50%;
  z-index: 30;
  pointer-events: none;
`;

const DarkOverlay = styled.div`
  position: absolute;
  inset: 0;
  background: rgba(0, 0, 0, 0.25);
  z-index: 25;
  pointer-events: none;
`;

const MessageDisplay = styled.div`
  position: absolute;
  bottom: 120px;
  left: 0;
  right: 0;
  text-align: center;
  z-index: 40;
  padding: 0 24px;
`;

const MessageText = styled.div`
  font-size: 1.4rem;
  line-height: 1.5;
  font-weight: 500;
  color: white;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.8);
  max-width: 85%;
  margin: 0 auto;
  animation: ${fadeIn} 0.3s ease;
`;

const CenteredMessage = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  z-index: 40;
  padding: 0 40px;
  background: #000;
`;

const CenteredText = styled.div`
  font-size: 1.8rem;
  line-height: 1.5;
  font-weight: 500;
  color: white;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.5);
  max-width: 85%;
  margin: 0 auto;
  animation: ${fadeIn} 0.3s ease;
`;

const EndorsementMeta = styled.div`
  position: absolute;
  bottom: 40px;
  left: 0;
  right: 0;
  display: flex;
  justify-content: center;
  gap: 32px;
  z-index: 40;
`;

const MetaItem = styled.div`
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.8rem;
  color: white;
  text-shadow: 0 1px 4px rgba(0, 0, 0, 0.5);
  background: rgba(0, 0, 0, 0.4);
  backdrop-filter: blur(8px);
  padding: 6px 14px;
  border-radius: 30px;

  svg {
    width: 14px;
    height: 14px;
    color: #dc2626;
  }
`;

const RightActions = styled.div`
  position: absolute;
  right: 16px;
  bottom: 30%;
  display: flex;
  flex-direction: column;
  gap: 20px;
  z-index: 50;
`;

const ActionButton = styled.button`
  display: flex;
  flex-direction: column;
  align-items: center;
  background: rgba(0, 0, 0, 0.6);
  backdrop-filter: blur(8px);
  border: none;
  padding: 10px;
  color: white;
  gap: 4px;
  cursor: pointer;
  min-width: 52px;
  border-radius: 30px;
  transition: all 0.2s;

  span {
    font-size: 0.65rem;
    font-weight: 600;
  }

  &:active {
    transform: scale(0.95);
  }

  &:hover {
    background: rgba(0, 0, 0, 0.8);
  }
`;

const CountSpan = styled.span`
  font-size: 0.65rem;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.9);
`;

const NavigationZone = styled.div`
  position: absolute;
  top: 0;
  bottom: 0;
  width: 30%;
  z-index: 40;
`;

const LeftZone = styled(NavigationZone)`
  left: 0;
`;
const RightZone = styled(NavigationZone)`
  right: 0;
`;

const CommentsModalOverlay = styled.div`
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #0a0a0a;
  height: 70vh;
  z-index: 100001;
  display: flex;
  flex-direction: column;
  animation: ${slideUp} 0.3s ease-out;
  border-radius: 20px 20px 0 0;
`;

const CommentsModalHeader = styled.div`
  padding: 16px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
`;

const CommentsList = styled.div`
  flex: 1;
  overflow-y: auto;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;

  &::-webkit-scrollbar {
    width: 4px;
  }

  &::-webkit-scrollbar-track {
    background: #1a1a1a;
  }

  &::-webkit-scrollbar-thumb {
    background: #dc2626;
    border-radius: 4px;
  }
`;

const CommentItem = styled.div`
  display: flex;
  gap: 12px;
  animation: fadeIn 0.2s ease;
`;

const CommentAvatar = styled.div`
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: linear-gradient(135deg, #dc2626, #b91c1c);
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-weight: bold;
  flex-shrink: 0;
`;

const CommentContent = styled.div`
  flex: 1;
`;

const CommentHeader = styled.div`
  display: flex;
  align-items: baseline;
  gap: 8px;
  margin-bottom: 6px;
  flex-wrap: wrap;
`;

const CommentUserName = styled.span`
  font-weight: 700;
  font-size: 0.9rem;
  color: white;
`;

const CommentTime = styled.span`
  font-size: 0.7rem;
  color: rgba(255, 255, 255, 0.5);
`;

const CommentText = styled.div`
  font-size: 0.95rem;
  color: rgba(255, 255, 255, 0.95);
  line-height: 1.5;
  word-break: break-word;
`;

const CommentActions = styled.div`
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 8px;
`;

const LikeButton = styled.button`
  background: none;
  border: none;
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.75rem;
  color: ${(props) => (props.$liked ? "#ef4444" : "rgba(255, 255, 255, 0.5)")};
  cursor: pointer;
  padding: 4px 8px;
  border-radius: 20px;
  transition: all 0.2s;

  &:hover {
    background: rgba(255, 255, 255, 0.1);
  }

  svg {
    width: 16px;
    height: 16px;
  }
`;

const CommentInputWrapper = styled.div`
  padding: 16px;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  background: #0a0a0a;
`;

const InputForm = styled.form`
  display: flex;
  gap: 12px;
  align-items: flex-end;
`;

const CommentInput = styled.textarea`
  flex: 1;
  background: #1a1a1a;
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 20px;
  padding: 12px 16px;
  color: white;
  font-size: 0.9rem;
  resize: none;
  min-height: 44px;
  max-height: 100px;
  font-family: inherit;

  &:focus {
    outline: none;
    border-color: #dc2626;
  }

  &::placeholder {
    color: rgba(255, 255, 255, 0.4);
    font-size: 0.85rem;
  }
`;

const SendButton = styled.button`
  background: #dc2626;
  border: none;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s;

  &:hover {
    background: #b91c1c;
    transform: scale(1.05);
  }

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
  }
`;

const EmptyComments = styled.div`
  text-align: center;
  color: rgba(255, 255, 255, 0.5);
  padding: 40px 20px;
  font-size: 0.9rem;
`;

const EndorsementDetailModal = ({
  isOpen,
  onClose,
  endorsements = [],
  initialIndex = 0,
  currentUser,
  onCommentsUpdate,
}) => {
  const [currentIndex, setCurrentIndex] = useState(initialIndex);
  const [progress, setProgress] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  const [showComments, setShowComments] = useState(false);
  const [showBoostModal, setShowBoostModal] = useState(false);
  const [likesState, setLikesState] = useState({});
  const [likesCountState, setLikesCountState] = useState({});
  const [commentsState, setCommentsState] = useState({});
  const [commentsLoading, setCommentsLoading] = useState({});
  const [newComment, setNewComment] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const timerRef = useRef(null);
  const STORY_DURATION = 5000;

  const current = endorsements[currentIndex];

  const loadComments = useCallback(async (storyId) => {
    if (!storyId) return;
    setCommentsLoading((prev) => ({ ...prev, [storyId]: true }));
    try {
      const response = await api.get(`/endorsements/${storyId}/comments`);
      let comments = [];
      if (response.data.data?.comments) {
        comments = response.data.data.comments;
      } else if (response.data.comments) {
        comments = response.data.comments;
      } else if (Array.isArray(response.data.data)) {
        comments = response.data.data;
      } else if (Array.isArray(response.data)) {
        comments = response.data;
      }
      setCommentsState((prev) => ({ ...prev, [storyId]: comments }));
    } catch (error) {
      setCommentsState((prev) => ({ ...prev, [storyId]: [] }));
    } finally {
      setCommentsLoading((prev) => ({ ...prev, [storyId]: false }));
    }
  }, []);

  useEffect(() => {
    if (isOpen && current?.id) {
      loadComments(current.id);
      if (
        current.likes !== undefined &&
        likesCountState[current.id] === undefined
      ) {
        setLikesCountState((prev) => ({
          ...prev,
          [current.id]: current.likes || 0,
        }));
      }
    }
  }, [isOpen, current?.id, loadComments, current?.likes]);

  const getAvatarUrl = (item) => {
    if (item?.image_url) {
      return buildImageUrl(item.image_url);
    }
    return `https://ui-avatars.com/api/?name=${encodeURIComponent(item?.user_name || "User")}&background=dc2626&color=fff&size=100`;
  };

  const getMediaUrl = (item) => {
    if (item?.image_url) {
      return buildImageUrl(item.image_url);
    }
    return null;
  };

  const formatDate = (dateString) => {
    if (!dateString) return "Recently";
    const date = new Date(dateString);
    const now = new Date();
    const diffMins = Math.floor((now - date) / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);

    if (diffMins < 1) return "Just now";
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  const capitalizeFirst = (str) => {
    if (!str) return "";
    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
  };

  useEffect(() => {
    if (isOpen) {
      setCurrentIndex(initialIndex);
      setProgress(0);
    }
  }, [isOpen, initialIndex]);

  const handleNext = useCallback(() => {
    if (currentIndex < endorsements.length - 1) {
      setCurrentIndex((prev) => prev + 1);
      setProgress(0);
    } else {
      onClose();
    }
  }, [currentIndex, endorsements.length, onClose]);

  const handlePrev = useCallback(() => {
    if (currentIndex > 0) {
      setCurrentIndex((prev) => prev - 1);
      setProgress(0);
    }
  }, [currentIndex]);

  useEffect(() => {
    if (!isOpen || isPaused || showComments || showBoostModal) return;

    const interval = 100;
    const step = 100 / (STORY_DURATION / interval);

    timerRef.current = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          handleNext();
          return 0;
        }
        return prev + step;
      });
    }, interval);

    return () => clearInterval(timerRef.current);
  }, [isOpen, isPaused, showComments, showBoostModal, handleNext]);

  const handleLike = async () => {
    if (!current) return;
    const storyId = current.id;
    const isLiked = likesState[storyId];
    const currentLikes = likesCountState[storyId] || current.likes || 0;

    setLikesState((prev) => ({ ...prev, [storyId]: !isLiked }));
    setLikesCountState((prev) => ({
      ...prev,
      [storyId]: isLiked ? currentLikes - 1 : currentLikes + 1,
    }));

    try {
      const response = await axios.post(
        `${API_BASE_URL}/api/v1/endorsements/${storyId}/like`,
        { user_id: currentUser?.id || "anonymous" },
      );
      if (response.data.success) {
        setLikesState((prev) => ({ ...prev, [storyId]: response.data.liked }));
        setLikesCountState((prev) => ({
          ...prev,
          [storyId]: response.data.likes,
        }));
        if (response.data.likes !== undefined && current) {
          current.likes = response.data.likes;
        }
      }
    } catch (e) {
      setLikesState((prev) => ({ ...prev, [storyId]: isLiked }));
      setLikesCountState((prev) => ({ ...prev, [storyId]: currentLikes }));
    }
  };

  const handleSendComment = async () => {
    if (!current || !newComment.trim() || isSubmitting) return;

    const storyId = current.id;
    const tempId = `temp_${Date.now()}`;

    setIsSubmitting(true);

    const newCommentObj = {
      id: tempId,
      user_id: currentUser?.id || "anonymous",
      user_name: currentUser?.name || "Anonymous",
      comment: newComment.trim(),
      created_at: new Date().toISOString(),
      likes: 0,
      liked: false,
    };

    setCommentsState((prev) => ({
      ...prev,
      [storyId]: [...(prev[storyId] || []), newCommentObj],
    }));

    setNewComment("");

    try {
      const response = await axios.post(
        `${API_BASE_URL}/api/v1/endorsements/${storyId}/comments`,
        {
          user_id: currentUser?.id || "anonymous",
          user_name: currentUser?.name || "Anonymous",
          comment: newComment.trim(),
          user_avatar: null,
        },
        {
          headers: { "Content-Type": "application/json" },
        },
      );

      if (response.data.success && response.data.data) {
        setCommentsState((prev) => ({
          ...prev,
          [storyId]: prev[storyId].map((c) =>
            c.id === tempId ? response.data.data : c,
          ),
        }));

        if (onCommentsUpdate) {
          onCommentsUpdate(storyId, response.data.data);
        }
      } else {
        setCommentsState((prev) => ({
          ...prev,
          [storyId]: prev[storyId].filter((c) => c.id !== tempId),
        }));
      }
    } catch (error) {
      setCommentsState((prev) => ({
        ...prev,
        [storyId]: prev[storyId].filter((c) => c.id !== tempId),
      }));
      setNewComment(newCommentObj.comment);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleLikeComment = async (commentId) => {
    if (!current) return;

    try {
      const response = await api.post(`/endorsements/${current.id}/comments/${commentId}/like`, 
        { user_id: currentUser?.id || "anonymous" }
      );

      if (response.data.success) {
        setCommentsState((prev) => ({
          ...prev,
          [current.id]: prev[current.id].map((c) =>
            c.id === commentId
              ? { ...c, liked: response.data.liked, likes: response.data.likes }
              : c,
          ),
        }));
      }
    } catch (error) {
      // Silent fail
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendComment();
    }
  };

  if (!isOpen || !current) return null;

  const currentLikesCount =
    likesCountState[current.id] !== undefined
      ? likesCountState[current.id]
      : current.likes || 0;

  const currentCommentsCount = commentsState[current.id]?.length || 0;
  const mediaUrl = getMediaUrl(current);
  const hasMedia =
    mediaUrl &&
    (current.media_type === "image" || current.media_type === "video");
  const isVideo = hasMedia && current.media_type === "video";
  const displayMessage = getDisplayMessage(current);

  // Don't show if no message and no media
  if (!displayMessage && !hasMedia) return null;

  return (
    <>
      <FullScreenOverlay>
        <ProgressContainer>
          {endorsements.map((_, idx) => (
            <ProgressTrack key={idx}>
              <ProgressFill
                $active={idx === currentIndex}
                $width={
                  idx < currentIndex ? 100 : idx === currentIndex ? progress : 0
                }
              />
            </ProgressTrack>
          ))}
        </ProgressContainer>

        <StoryHeader>
          <UserInfo>
            <UserAvatar src={getAvatarUrl(current)} alt={current.user_name} />
            <UserTextInfo>
              <UserName>
                {capitalizeFirst(current.user_name || "Anonymous")}
              </UserName>
              <UserDetail>
                <Clock size={10} />
                <span>{formatDate(current.created_at)}</span>
              </UserDetail>
            </UserTextInfo>
          </UserInfo>
          <CloseBtn onClick={onClose}>
            <X size={20} />
          </CloseBtn>
        </StoryHeader>

        <LeftZone onClick={handlePrev} />
        <RightZone onClick={handleNext} />

        {hasMedia ? (
          <>
            <FullScreenMedia>
              {isVideo ? (
                <video src={mediaUrl} autoPlay loop playsInline />
              ) : (
                <img src={mediaUrl} alt="Story" />
              )}
            </FullScreenMedia>
            <DarkOverlay />
            <GradientOverlay />
          </>
        ) : null}

        {displayMessage && hasMedia && (
          <MessageDisplay>
            <MessageText>{displayMessage}</MessageText>
          </MessageDisplay>
        )}

        {displayMessage && !hasMedia && (
          <CenteredMessage>
            <CenteredText>{displayMessage}</CenteredText>
          </CenteredMessage>
        )}

        <EndorsementMeta>
          <MetaItem>
            <Heart size={14} />
            <span>{currentLikesCount}</span>
          </MetaItem>
          <MetaItem>
            <MessageCircle size={14} />
            <span>{currentCommentsCount}</span>
          </MetaItem>
        </EndorsementMeta>

        <RightActions>
          <ActionButton onClick={handleLike}>
            <Heart
              size={22}
              fill={likesState[current.id] ? "#ef4444" : "none"}
              color={likesState[current.id] ? "#ef4444" : "white"}
            />
            <span>Like</span>
            <CountSpan>{currentLikesCount}</CountSpan>
          </ActionButton>

          <ActionButton onClick={() => setShowComments(true)}>
            <MessageCircle size={22} />
            <span>Chat</span>
            <CountSpan>{currentCommentsCount}</CountSpan>
          </ActionButton>

          <ActionButton onClick={() => setShowBoostModal(true)}>
            <TrendingUp size={22} color="#fbbf24" />
            <span>Boost</span>
            <CountSpan>{current.boost_count || 0}</CountSpan>
          </ActionButton>
        </RightActions>

        {showComments && (
          <CommentsModalOverlay>
            <CommentsModalHeader>
              <div
                style={{ color: "white", fontWeight: "bold", fontSize: "1rem" }}
              >
                Comments ({currentCommentsCount})
              </div>
              <CloseBtn onClick={() => setShowComments(false)}>
                <X size={18} />
              </CloseBtn>
            </CommentsModalHeader>

            <CommentsList>
              {commentsLoading[current.id] ? (
                <div
                  style={{
                    padding: "40px",
                    textAlign: "center",
                    color: "white",
                  }}
                >
                  Loading comments...
                </div>
              ) : commentsState[current.id]?.length === 0 ? (
                <EmptyComments>
                  No comments yet. Be the first to comment!
                </EmptyComments>
              ) : (
                commentsState[current.id]?.map((comment) => (
                  <CommentItem key={comment.id}>
                    <CommentAvatar>
                      {comment.user_name?.charAt(0).toUpperCase() || "U"}
                    </CommentAvatar>
                    <CommentContent>
                      <CommentHeader>
                        <CommentUserName>
                          {comment.user_name || "Anonymous"}
                        </CommentUserName>
                        <CommentTime>
                          {formatDate(comment.created_at)}
                        </CommentTime>
                      </CommentHeader>
                      <CommentText>{comment.comment}</CommentText>
                      <CommentActions>
                        <LikeButton
                          $liked={comment.liked}
                          onClick={() => handleLikeComment(comment.id)}
                        >
                          <Heart
                            size={14}
                            fill={comment.liked ? "#ef4444" : "none"}
                          />
                          <span>{comment.likes || 0}</span>
                        </LikeButton>
                      </CommentActions>
                    </CommentContent>
                  </CommentItem>
                ))
              )}
            </CommentsList>

            <CommentInputWrapper>
              <InputForm
                onSubmit={(e) => {
                  e.preventDefault();
                  handleSendComment();
                }}
              >
                <CommentInput
                  placeholder="Write a comment..."
                  value={newComment}
                  onChange={(e) => setNewComment(e.target.value)}
                  onKeyPress={handleKeyPress}
                  rows={1}
                />
                <SendButton
                  type="submit"
                  disabled={!newComment.trim() || isSubmitting}
                >
                  <Send size={18} color="white" />
                </SendButton>
              </InputForm>
            </CommentInputWrapper>
          </CommentsModalOverlay>
        )}
      </FullScreenOverlay>

      {showBoostModal && (
        <BoostModal
          isOpen={showBoostModal}
          onClose={() => setShowBoostModal(false)}
          endorsementId={current.id}
          targetName={current.user_name}
        />
      )}
    </>
  );
};

export default EndorsementDetailModal;
