// components/endorsements/EndorsementStories.jsx 

import React, { useState, useEffect, useCallback } from "react";
import styled, { keyframes } from "styled-components";
import {
  Plus,
  TrendingUp,
  MessageCircle,
  AlertCircle,
  RefreshCw,
  CheckCircle,
  Play,
} from "lucide-react";
import theme from "../../utils/theme";
import AddStoryModal from "./addStoryModal";
import EndorsementDetailModal from "./EndorsementDetailModal";
import { buildImageUrl } from "../../utils/imageUtils";

const isAutoGeneratedMessage = (message, mediaType) => {
  if (!message) return true;

  const autoMessages = [
    "📷 Photo",
    "📹 Video",
    "💬 Support message",
    "Support message",
    "Photo",
    "Video",
  ];

  if (
    (mediaType === "image" || mediaType === "video") &&
    autoMessages.includes(message.trim())
  ) {
    return true;
  }

  return false;
};

const getDisplayMessage = (story) => {
  const { message, media_type } = story;

  if (message && !isAutoGeneratedMessage(message, media_type)) {
    return message;
  }

  return null;
};

// ============================================
// MAIN COMPONENT
// ============================================

const EndorsementStories = ({ leaderId, currentUser, onBoostSuccess }) => {
  const [showAddModal, setShowAddModal] = useState(false);
  const [showStoryModal, setShowStoryModal] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [replies, setReplies] = useState({});
  const [endorsements, setEndorsements] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showSuccess, setShowSuccess] = useState(false);
  const [successMessage, setSuccessMessage] = useState("");

  const fetchEndorsements = useCallback(async () => {
    if (!leaderId) {
      setLoading(false);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const path = `/endorsements/leader/${leaderId}/recent?limit=100`;

      const responseData = await api.get(path);

      if (responseData.success) {
        setEndorsements(responseData.data || []);
      } else {
        setError(responseData.message || "Failed to load stories");
        setEndorsements([]);
      }

    } catch (error) {
      console.error("❌ Error fetching endorsements:", error);
      setError(error.response?.data?.message || "Failed to load stories");
      setEndorsements([]);
    } finally {
      setLoading(false);
    }
  }, [leaderId]);

  useEffect(() => {
    fetchEndorsements();
  }, [fetchEndorsements]);

  useEffect(() => {
    const savedReplies = localStorage.getItem("story_replies");
    if (savedReplies) {
      try {
        setReplies(JSON.parse(savedReplies));
      } catch (e) {
        console.error("Failed to parse saved replies:", e);
      }
    }
  }, []);

  useEffect(() => {
    if (Object.keys(replies).length) {
      localStorage.setItem("story_replies", JSON.stringify(replies));
    }
  }, [replies]);

  const handleAddStoryClick = () => setShowAddModal(true);

  const handleStoryClick = (index) => {
    setSelectedIndex(index);
    setShowStoryModal(true);
  };

  const handleReply = (storyId, reply) => {
    setReplies((prev) => ({
      ...prev,
      [storyId]: [reply, ...(prev[storyId] || [])],
    }));
  };

  const hasReplies = (storyId) => {
    return (replies[storyId]?.length || 0) > 0;
  };

  const handleRefresh = () => {
    fetchEndorsements();
  };

  const handleStoryPosted = () => {
    setSuccessMessage("Story posted successfully!");
    setShowSuccess(true);
    fetchEndorsements();
    setTimeout(() => {
      setShowSuccess(false);
    }, 3000);
  };

  const getMediaIcon = (mediaType) => {
    if (mediaType === "video") return "🎬";
    if (mediaType === "image") return "📷";
    return "💬";
  };

  // FIXED: Better error handling for images
  const getStoryPreview = (story) => {
    const { media_type, image_url, user_name, message } = story;

    const imageSrc = buildImageUrl(image_url);

    // Image story
    if (media_type === "image" && imageSrc) {
      return (
        <StoryImage
          src={imageSrc}
          alt={user_name || "Story"}
          onError={(e) => {
            console.warn(`Failed to load image: ${imageSrc}`);
            e.target.style.display = "none";
            // Show fallback text in parent
            if (e.target.parentElement) {
              const fallback = document.createElement('div');
              fallback.style.cssText = 'width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:#1e3c72;color:white;font-size:24px;';
              fallback.innerText = '📷';
              e.target.parentElement.appendChild(fallback);
              e.target.remove();
            }
          }}
        />
      );
    }

    // Video story
    if (media_type === "video" && imageSrc) {
      return (
        <>
          <StoryImage
            src={imageSrc}
            alt={user_name || "Video"}
            onError={(e) => {
              console.warn(`Failed to load video thumbnail: ${imageSrc}`);
              e.target.style.display = "none";
            }}
          />
          <VideoPlayIcon>
            <Play size={14} />
          </VideoPlayIcon>
        </>
      );
    }

    // Text story
    const displayMessage = getDisplayMessage(story);
    if (displayMessage) {
      return (
        <TextStoryPreview>
          {displayMessage.length > 60 ? displayMessage.substring(0, 60) + "..." : displayMessage}
        </TextStoryPreview>
      );
    }

    // Fallback
    return <TextStoryPreview>💬 Support</TextStoryPreview>;
  };

  // Filter valid endorsements (has image OR real message)
  const validEndorsements = endorsements.filter((e) => {
    if (e.image_url) return true;
    const hasRealMessage =
      e.message && !isAutoGeneratedMessage(e.message, e.media_type);
    return hasRealMessage;
  });

  return (
    <>
      <StoriesSection>
        <StoriesContainer>
          <StoriesHeader>
            <StoriesTitle>
              <TrendingUp
                size={14}
                color={theme.colors?.primary || "#ff5c01"}
              />
              STORIES
            </StoriesTitle>
            <RefreshButton onClick={handleRefresh} title="Refresh stories">
              <RefreshCw size={14} />
            </RefreshButton>
          </StoriesHeader>

          <StoriesScroll>
            {/* Add Story Button */}
            <StoryItem onClick={handleAddStoryClick}>
              <StoryRing $isAdd>
                <StoryAvatar $isAdd>
                  <Plus size={24} color={theme.colors?.primary || "#ff5c01"} />
                </StoryAvatar>
              </StoryRing>
              <StoryName>Your Story</StoryName>
            </StoryItem>

            {loading ? (
              [...Array(6)].map((_, i) => (
                <StoryItem key={`loader-${i}`}>
                  <LoadingShimmer />
                  <StoryName>...</StoryName>
                </StoryItem>
              ))
            ) : error ? (
              <EmptyState>
                <AlertCircle size={32} />
                <p>{error}</p>
                <RefreshButton onClick={handleRefresh} style={{ marginTop: 8 }}>
                  Try Again
                </RefreshButton>
              </EmptyState>
            ) : validEndorsements.length === 0 ? (
              <EmptyState>
                <MessageCircle size={32} />
                <p>No stories yet. Be the first to support!</p>
              </EmptyState>
            ) : (
              validEndorsements.map((supporter, index) => {
                const hasRepliesCount = hasReplies(supporter.id);
                const latestReply = replies[supporter.id]?.[0];
                const mediaType = supporter.media_type || "text";

                return (
                  <StoryItem
                    key={supporter.id}
                    onClick={() => handleStoryClick(index)}
                  >
                    <StoryRing $hasReplies={hasRepliesCount}>
                      <StoryAvatar>
                        {getStoryPreview(supporter)}
                        {hasRepliesCount && (
                          <ReplyBadge>
                            <MessageCircle size={10} />
                          </ReplyBadge>
                        )}
                        <MediaTypeBadge>
                          {getMediaIcon(mediaType)}
                        </MediaTypeBadge>
                      </StoryAvatar>
                    </StoryRing>
                    <StoryName>
                      {supporter.user_name?.split(" ")[0] || "Anonymous"}
                    </StoryName>
                    {latestReply && (
                      <div
                        style={{
                          fontSize: "8px",
                          color: "#10b981",
                          maxWidth: "76px",
                          overflow: "hidden",
                          textOverflow: "ellipsis",
                          whiteSpace: "nowrap",
                          marginTop: "-4px",
                          textAlign: "center",
                        }}
                      >
                        💬 {latestReply.user_name?.split(" ")[0]}
                      </div>
                    )}
                  </StoryItem>
                );
              })
            )}
          </StoriesScroll>
        </StoriesContainer>
      </StoriesSection>

      <AddStoryModal
        isOpen={showAddModal}
        onClose={() => setShowAddModal(false)}
        leader={leaderId}
        user={currentUser}
        onComplete={handleStoryPosted}
      />

      <EndorsementDetailModal
        isOpen={showStoryModal}
        onClose={() => setShowStoryModal(false)}
        endorsements={validEndorsements}
        initialIndex={selectedIndex}
        getImageUrl={buildImageUrl}
        currentUser={currentUser}
        onReply={handleReply}
        onBoost={onBoostSuccess}
        leaderId={leaderId}
      />

      {showSuccess && (
        <SuccessToast>
          <CheckCircle size={16} />
          {successMessage}
        </SuccessToast>
      )}
    </>
  );
};

export default EndorsementStories;
