version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8009:8009"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=8009
      - LEADERS_SERVICE_URL=http://leaders-service:8006
      - MEDIA_SERVICE_URL=http://media-service:8007
      - RALLY_SERVICE_URL=http://rally-service:8001
      - USERS_SERVICE_URL=http://users-service:8002
      - WALLET_SERVICE_URL=http://wallet-service:8008
      - ENDORSEMENT_SERVICE_URL=http://endorsement-service:8003
      - MARKETPLACE_SERVICE_URL=http://marketplace-service:8004
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  users-service:
    build: ./users-service
    container_name: users-service
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=8002

  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=8008

  leaders-service:
    build: ./leaders-service
    container_name: leaders-service
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=8006

  rally-service:
    build: ./rally-service
    container_name: rally-service
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=8001

  endorsement-service:
    build: ./endorsement-service
    container_name: endorsement-service
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=8003

  marketplace-service:
    build: ./marketplace-service
    container_name: marketplace-service
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - PORT=8004

  redis:
    image: redis:alpine
    container_name: shared-redis
    ports:
      - "6379:6379"

volumes:
  redis-data: